/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Conexion.ConexionBD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Jiro
 */
public class lobby extends VentanaControladaAbstract {
private DefaultTableModel modelo = new DefaultTableModel(); 
    /**
     * Creates new form lobby2
     */
    public lobby() {
    this.modelo.addColumn("Nombre");
    this.modelo.addColumn("Hora");
    initComponents();
    setLocationRelativeTo(null);
    this.users.setVisible(false);
    this.tblCitasDIaLobby.setEnabled(false);
    this.btnCitasLobby.setActionCommand("citas");
    this.btnCitasLobby.addActionListener(this);
    this.btnPacientesLobby.setActionCommand("pacientes");
    this.btnPacientesLobby.addActionListener(this);
    this.btnReportesLobby.setActionCommand("reportes");
    this.btnReportesLobby.addActionListener(this);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCitasDIaLobby = new javax.swing.JTable();
        btnCitasLobby = new javax.swing.JButton();
        btnPacientesLobby = new javax.swing.JButton();
        btnReportesLobby = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        users = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("Citas del Dia");

        tblCitasDIaLobby.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCitasDIaLobby.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCitasDIaLobby);
        if (tblCitasDIaLobby.getColumnModel().getColumnCount() > 0) {
            tblCitasDIaLobby.getColumnModel().getColumn(0).setMinWidth(300);
            tblCitasDIaLobby.getColumnModel().getColumn(0).setPreferredWidth(300);
            tblCitasDIaLobby.getColumnModel().getColumn(0).setMaxWidth(300);
            tblCitasDIaLobby.getColumnModel().getColumn(1).setResizable(false);
        }

        btnCitasLobby.setText("Citas");
        btnCitasLobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasLobbyActionPerformed(evt);
            }
        });

        btnPacientesLobby.setText("Pacientes");
        btnPacientesLobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesLobbyActionPerformed(evt);
            }
        });

        btnReportesLobby.setText("Reportes");
        btnReportesLobby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesLobbyActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        users.setText("Usuarios");
        users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPacientesLobby, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCitasLobby, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReportesLobby, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCitasLobby)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPacientesLobby)
                        .addGap(18, 18, 18)
                        .addComponent(btnReportesLobby)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(users)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCitasLobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasLobbyActionPerformed
        // TODO add your handling code here:
        this.superCtrl.muestraVentanaCitas(true);
    }//GEN-LAST:event_btnCitasLobbyActionPerformed

    private void btnPacientesLobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesLobbyActionPerformed
        // TODO add your handling code here:
        this.superCtrl.muestraVentanaPacientes(true);
    }//GEN-LAST:event_btnPacientesLobbyActionPerformed

    private void btnReportesLobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesLobbyActionPerformed
        // TODO add your handling code here:
        this.superCtrl.muestraVentanaReportes(true);
    }//GEN-LAST:event_btnReportesLobbyActionPerformed

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
        // TODO add your handling code here:
        this.superCtrl.muestraVentanaus(true);
    }//GEN-LAST:event_usersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lobby().setVisible(true);
            }
        });
    }
  public void consulta() {
      if(!"admin".equals(this.superCtrl.getUser())){
        this.users.setVisible(false);
    }else{
        this.users.setVisible(true);
    }
    try {
        
      this.modelo.setRowCount(0);
      PreparedStatement st = null;
      ResultSet rt = null;
      ConexionBD con = new ConexionBD();
      Connection cn = con.getConexion();
      String sql = "SELECT nombre_completo(id_paciente) as nombre,to_char(consultas.fecha_hora_pc,'HH:MI:SS') as hora FROM consultas NATURAL JOIN paciente where TO_CHAR(consultas.fecha_hora_pc,'DD/MM/YY')=(select TO_CHAR(current_date,'DD/MM/YY') from dual)";
      st = cn.prepareStatement(sql);
      rt = st.executeQuery();
      
      ResultSetMetaData rsMd = rt.getMetaData();
      int cantcolumnas = rsMd.getColumnCount();
        //System.out.println(rsMd.getColumnCount());
        //System.out.println(rsMd.toString());
      while (rt.next()) {
          //System.out.println("1");
        Object[] filas = new Object[cantcolumnas];
        for (int i = 0; i < cantcolumnas; i++) {
          filas[i] = rt.getObject(i + 1);
            //System.out.println(filas[i]);
        }
        this.modelo.addRow(filas);
      } 
      
      this.tblCitasDIaLobby.setModel(this.modelo);
      tblCitasDIaLobby.getColumnModel().getColumn(0).setMinWidth(300);
      tblCitasDIaLobby.getColumnModel().getColumn(0).setPreferredWidth(300);
      tblCitasDIaLobby.getColumnModel().getColumn(0).setMaxWidth(300);
      tblCitasDIaLobby.getColumnModel().getColumn(1).setResizable(false);
    } catch (SQLException e) {
      JOptionPane.showMessageDialog(this, "Ocurrio un error durante la consulta");
    } 
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCitasLobby;
    private javax.swing.JButton btnPacientesLobby;
    private javax.swing.JButton btnReportesLobby;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCitasDIaLobby;
    private javax.swing.JButton users;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
