/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Conexion.ConexionBD;
import java.awt.Toolkit;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
/**
 *
 * @author Jiro
 */
public class VentanaBuscarPaciente extends VentanaControladaAbstract {
    private ConexionBD con;
  private PreparedStatement st;
  private ResultSet rt;
    /**
     * Creates new form VentanaBuscarPaciente
     */
    public VentanaBuscarPaciente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTelefonoPacienteAgregar = new javax.swing.JLabel();
        lblCorreoPacienteAgregar = new javax.swing.JLabel();
        lblCpPacienteAgregar = new javax.swing.JLabel();
        lblNoInPacienteAgregar = new javax.swing.JLabel();
        lblNoExPacienteAgregar = new javax.swing.JLabel();
        lblCallePacienteAgregar = new javax.swing.JLabel();
        lblColoniaPacienteAgregar = new javax.swing.JLabel();
        lblCiudadPacienteAgregar = new javax.swing.JLabel();
        lblEstadoPacienteAgregar = new javax.swing.JLabel();
        btnCancelarPacienteBuscar = new javax.swing.JButton();
        lblNombrePacienteAgregar = new javax.swing.JLabel();
        lblApellidosPacienteAgregar = new javax.swing.JLabel();
        lblGeneroPacienteAgregar = new javax.swing.JLabel();
        lblEdoCivilPacienteAgregar = new javax.swing.JLabel();
        lblOcupacionPacienteAgregar = new javax.swing.JLabel();
        btnEliminarPaciente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtClaveBuscarPaciente = new javax.swing.JTextField();
        btnBuscarPaciente = new javax.swing.JButton();
        txtNombreBuscarPaciente = new javax.swing.JTextField();
        txtApellidosBuscarPaciente = new javax.swing.JTextField();
        txtOcupacionBuscarPaciente = new javax.swing.JTextField();
        txtTelefonoBuscarPaciente = new javax.swing.JTextField();
        txtCorreoBuscarPaciente = new javax.swing.JTextField();
        cbGeneroBuscarPaciente = new javax.swing.JComboBox<>();
        cbEdoCivilBuscarPaciente = new javax.swing.JComboBox<>();
        cbEdoBuscarPaciente = new javax.swing.JComboBox<>();
        txtCiudadBuscarPaciente = new javax.swing.JTextField();
        txtColoniaBuscarPaciente = new javax.swing.JTextField();
        txtCalleBuscarPaciente = new javax.swing.JTextField();
        txtNoExBuscarPaciente = new javax.swing.JTextField();
        txtNoInBuscarPaciente = new javax.swing.JTextField();
        txtCpBuscarPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTelefonoPacienteAgregar.setText("Telefono:");

        lblCorreoPacienteAgregar.setText("Correo:");

        lblCpPacienteAgregar.setText("C.P.");

        lblNoInPacienteAgregar.setText("No. Int.");

        lblNoExPacienteAgregar.setText("No. Ext.");

        lblCallePacienteAgregar.setText("Calle:");

        lblColoniaPacienteAgregar.setText("Colonia:");

        lblCiudadPacienteAgregar.setText("Ciudad:");

        lblEstadoPacienteAgregar.setText("Estado:");

        btnCancelarPacienteBuscar.setText("Cancelar");
        btnCancelarPacienteBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPacienteBuscarActionPerformed(evt);
            }
        });

        lblNombrePacienteAgregar.setText("Nombre:");

        lblApellidosPacienteAgregar.setText("Apellidos:");

        lblGeneroPacienteAgregar.setText("Genero:");

        lblEdoCivilPacienteAgregar.setText("Estado Civil:");

        lblOcupacionPacienteAgregar.setText("Ocupacion:");

        btnEliminarPaciente.setText("Eliminar");
        btnEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPacienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Clave");

        txtClaveBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveBuscarPacienteKeyTyped(evt);
            }
        });

        btnBuscarPaciente.setText("Buscar");
        btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPacienteActionPerformed(evt);
            }
        });

        txtNombreBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBuscarPacienteActionPerformed(evt);
            }
        });
        txtNombreBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreBuscarPacienteKeyTyped(evt);
            }
        });

        txtApellidosBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosBuscarPacienteKeyTyped(evt);
            }
        });

        txtOcupacionBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOcupacionBuscarPacienteKeyTyped(evt);
            }
        });

        txtTelefonoBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoBuscarPacienteKeyTyped(evt);
            }
        });

        txtCorreoBuscarPaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoBuscarPacienteFocusLost(evt);
            }
        });
        txtCorreoBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoBuscarPacienteKeyTyped(evt);
            }
        });

        cbGeneroBuscarPaciente.setModel(new DefaultComboBoxModel(new String[] { "", "H", "M" }));

        cbEdoCivilBuscarPaciente.setModel(new DefaultComboBoxModel(new String[] { "", "Soltero", "Casado", "Divorciado" }));

        cbEdoBuscarPaciente.setModel(new DefaultComboBoxModel(new String[] { "", "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Coahuila", "Colima", "Durango", "Estado De M�xico", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Michoac�n", "Morelos", "Nayarit", "Nuevo Le�n", "Oaxaca", "Puebla", "Quer�taro", "Quintana Roo", "San Luis Potos�", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucat�n", "Zacatecas" }));

        txtCiudadBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCiudadBuscarPacienteKeyTyped(evt);
            }
        });

        txtColoniaBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColoniaBuscarPacienteKeyTyped(evt);
            }
        });

        txtCalleBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleBuscarPacienteActionPerformed(evt);
            }
        });
        txtCalleBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCalleBuscarPacienteKeyTyped(evt);
            }
        });

        txtNoExBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoExBuscarPacienteKeyTyped(evt);
            }
        });

        txtNoInBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoInBuscarPacienteKeyTyped(evt);
            }
        });

        txtCpBuscarPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCpBuscarPacienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelarPacienteBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarPaciente))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClaveBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarPaciente))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblCorreoPacienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTelefonoPacienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblApellidosPacienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblGeneroPacienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblOcupacionPacienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblEdoCivilPacienteAgregar))
                                    .addComponent(lblNombrePacienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblCallePacienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblColoniaPacienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCiudadPacienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblEstadoPacienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCpPacienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblNoExPacienteAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNoInPacienteAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidosBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbGeneroBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEdoCivilBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOcupacionBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorreoBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEdoBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCiudadBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtColoniaBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCalleBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoExBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoInBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClaveBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPaciente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePacienteAgregar)
                    .addComponent(txtNombreBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosPacienteAgregar)
                    .addComponent(txtApellidosBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeneroPacienteAgregar)
                    .addComponent(cbGeneroBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdoCivilPacienteAgregar)
                    .addComponent(cbEdoCivilBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOcupacionPacienteAgregar)
                    .addComponent(txtOcupacionBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoPacienteAgregar)
                    .addComponent(txtTelefonoBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoPacienteAgregar)
                    .addComponent(txtCorreoBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoPacienteAgregar)
                    .addComponent(cbEdoBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiudadPacienteAgregar)
                    .addComponent(txtCiudadBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColoniaPacienteAgregar)
                    .addComponent(txtColoniaBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCallePacienteAgregar)
                    .addComponent(txtCalleBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoExPacienteAgregar)
                    .addComponent(txtNoExBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoInPacienteAgregar)
                    .addComponent(txtNoInBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpPacienteAgregar)
                    .addComponent(txtCpBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarPaciente)
                    .addComponent(btnCancelarPacienteBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarPacienteBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPacienteBuscarActionPerformed
        /*if ("agregar".equals(evt.getActionCommand())) {
            limpiar();
            this.superCtrl.muestraVentanaPacientes(true);
        } else {
            limpiar();
            this.superCtrl.muestraVentanaModificarPacientes(true);
        }*/
        this.limpiar();
        this.superCtrl.muestraVentanaPacientes(true);
    }//GEN-LAST:event_btnCancelarPacienteBuscarActionPerformed

    private void txtNombreBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBuscarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBuscarPacienteActionPerformed

    private void txtNombreBuscarPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreBuscarPacienteKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNombreBuscarPacienteKeyTyped

    private void txtApellidosBuscarPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosBuscarPacienteKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtApellidosBuscarPacienteKeyTyped

    private void txtOcupacionBuscarPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOcupacionBuscarPacienteKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtOcupacionBuscarPacienteKeyTyped

    private void txtTelefonoBuscarPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoBuscarPacienteKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTelefonoBuscarPacienteKeyTyped

    private void txtCorreoBuscarPacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoBuscarPacienteFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCorreoBuscarPacienteFocusLost

    private void txtCorreoBuscarPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoBuscarPacienteKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCorreoBuscarPacienteKeyTyped

    private void txtCiudadBuscarPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudadBuscarPacienteKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCiudadBuscarPacienteKeyTyped

    private void txtColoniaBuscarPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColoniaBuscarPacienteKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtColoniaBuscarPacienteKeyTyped

    private void txtCalleBuscarPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalleBuscarPacienteKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCalleBuscarPacienteKeyTyped

    private void txtNoExBuscarPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoExBuscarPacienteKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNoExBuscarPacienteKeyTyped

    private void txtNoInBuscarPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoInBuscarPacienteKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNoInBuscarPacienteKeyTyped

    private void txtCpBuscarPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpBuscarPacienteKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCpBuscarPacienteKeyTyped

    private void txtCalleBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleBuscarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleBuscarPacienteActionPerformed

    private void btnEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPacienteActionPerformed
        // TODO add your handling code here:
        if ("eliminar".equals(evt.getActionCommand())) {
            if (JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar al paciente?\nSe eliminaran todos los registros donde aparezca este paciente\nESTA ACCION NO SE PUEDE DESHACER", "Alerta!", 0, 2) == 0) {
                this.con = new ConexionBD();
                final Connection cn = this.con.getConexion();
                //String sql = "DELETE FROM consultas WHERE id_paciente=?";
                String sql="exec paquetepaciente.delpaciente(?)";
                try {
                    (this.st = cn.prepareStatement(sql)).setString(1, this.superCtrl.getClave());
                    //this.st.executeUpdate();
                    //sql = "DELETE FROM cuestionario WHERE id_paciente=?";
                    //(this.st = cn.prepareStatement(sql)).setString(1, this.superCtrl.getClave());
                    //this.st.executeUpdate();
                    //sql = "DELETE FROM paciente WHERE id_paciente=? ";
                    //(this.st = cn.prepareStatement(sql)).setString(1, this.superCtrl.getClave());
                    this.st.executeUpdate();
                    cn.close();
                    this.con.desconectar();
                    this.st.close();
                    this.limpiar();
                    this.btnEliminarPaciente.setEnabled(false);
                    JOptionPane.showMessageDialog(this, "Se ha eliminado con exito!", "Atencion", 1);
                    this.superCtrl.muestraVentanaPacientes(true);
                }
                catch (HeadlessException | NumberFormatException | SQLException ex) {
                    final Exception e = ex;
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 0);
                }
            }
        }
        else {
            this.superCtrl.setClave(this.txtClaveBuscarPaciente.getText());
            this.limpiar();
            this.superCtrl.muestraVentanaModificarPacientes(false);
        }
    }//GEN-LAST:event_btnEliminarPacienteActionPerformed

    private void txtClaveBuscarPacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveBuscarPacienteKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
    if (Character.isLetter(validar)) {
      evt.consume();
      Toolkit.getDefaultToolkit().beep();
      JOptionPane.showMessageDialog(this.rootPane, "Ingrese solo numeros", "Atencion", 1);
    } else if (this.txtClaveBuscarPaciente.getText().length() >= 6) {
      evt.consume();
      Toolkit.getDefaultToolkit().beep();
    } 
    }//GEN-LAST:event_txtClaveBuscarPacienteKeyTyped

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed
        // TODO add your handling code here:
        this.con = new ConexionBD();
        final Connection cn = this.con.getConexion();
        final String sql = "SELECT * from paciente where rownum=1 and id_paciente=? order by id_paciente DESC";
        try {
            (this.st = cn.prepareStatement(sql)).setString(1, this.txtClaveBuscarPaciente.getText());
            this.rt = this.st.executeQuery();
            if (this.rt.next()) {
                this.txtNombreBuscarPaciente.setText(this.rt.getString("nombre"));
                this.txtApellidosBuscarPaciente.setText(this.rt.getString("apellidos"));
                this.txtOcupacionBuscarPaciente.setText(this.rt.getString("ocupacion"));
                this.txtTelefonoBuscarPaciente.setText(""+this.rt.getLong("tel"));
                this.txtCorreoBuscarPaciente.setText(this.rt.getString("email"));
                this.txtCiudadBuscarPaciente.setText(this.rt.getString("ciudad"));
                this.txtColoniaBuscarPaciente.setText(this.rt.getString("colonia"));
                this.txtCalleBuscarPaciente.setText(this.rt.getString("calle"));
                this.txtNoExBuscarPaciente.setText(this.rt.getInt("numero_exterior")+"");
                if (this.rt.getInt("numero_interior") != 0) {
                    this.txtNoInBuscarPaciente.setText(this.rt.getInt("numero_interior")+"");
                }
                else {
                    this.txtNoInBuscarPaciente.setText(null);
                }
                this.txtCpBuscarPaciente.setText(this.rt.getInt("cp")+"");
                if (this.rt.getInt("genero") == 1) {
                    this.cbGeneroBuscarPaciente.setSelectedItem("H");
                }
                else {
                    this.cbGeneroBuscarPaciente.setSelectedItem("M");
                }
                this.cbEdoCivilBuscarPaciente.setSelectedItem(this.formato(this.rt.getString("edo_civil")));
                this.cbEdoBuscarPaciente.setSelectedItem(this.formato(this.rt.getString("edo")));
                this.superCtrl.setClave(this.rt.getString("id_paciente"));
                cn.close();
                this.con.desconectar();
                this.rt.close();
                this.st.close();
                this.btnEliminarPaciente.setEnabled(true);
            }
            else {
                this.limpiar();
                this.btnEliminarPaciente.setEnabled(false);
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBuscarPaciente().setVisible(true);
            }
        });
    }

  public void buscar(boolean b) {
    this.btnEliminarPaciente.setEnabled(!b);
    this.btnEliminarPaciente.setVisible(!b);
  }
  
  public void eliminar(boolean b) {
    this.btnEliminarPaciente.setText("Eliminar");
    this.btnEliminarPaciente.setActionCommand("eliminar");
    this.btnEliminarPaciente.setEnabled(!b);
    this.btnEliminarPaciente.setVisible(b);
  }
  public void modificar(boolean b) {
    this.btnEliminarPaciente.setText("Modificar");
    this.btnEliminarPaciente.setActionCommand("modificar");
    this.btnEliminarPaciente.setEnabled(!b);
    this.btnEliminarPaciente.setVisible(b);
  }
  @Override
    public void actionPerformed(ActionEvent e) {}
    private void limpiar() {
    this.txtClaveBuscarPaciente.setText(null);
    this.txtNombreBuscarPaciente.setText(null);
    this.txtApellidosBuscarPaciente.setText(null);
    this.txtOcupacionBuscarPaciente.setText(null);
    this.txtTelefonoBuscarPaciente.setText(null);
    this.txtCorreoBuscarPaciente.setText(null);
    this.txtCiudadBuscarPaciente.setText(null);
    this.txtColoniaBuscarPaciente.setText(null);
    this.txtCalleBuscarPaciente.setText(null);
    this.txtNoExBuscarPaciente.setText(null);
    this.txtNoInBuscarPaciente.setText(null);
    this.txtCpBuscarPaciente.setText(null);
    this.cbEdoCivilBuscarPaciente.setSelectedIndex(0);
    this.cbEdoBuscarPaciente.setSelectedIndex(0);
    this.cbGeneroBuscarPaciente.setSelectedIndex(0);
  }
  
  private String formato(String string) {
    string = string.toLowerCase();
    char[] caracteres = string.toCharArray();
    caracteres[0] = Character.toUpperCase(caracteres[0]);
    
    for (int i = 0; i < string.length() - 2; i++) {
      
      if (caracteres[i] == ' ' || caracteres[i] == '.' || caracteres[i] == ',')
      {
        caracteres[i + 1] = Character.toUpperCase(caracteres[i + 1]);
      }
    } 
    return new String(caracteres);
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton btnCancelarPacienteBuscar;
    private javax.swing.JButton btnEliminarPaciente;
    private javax.swing.JComboBox<String> cbEdoBuscarPaciente;
    private javax.swing.JComboBox<String> cbEdoCivilBuscarPaciente;
    private javax.swing.JComboBox<String> cbGeneroBuscarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellidosPacienteAgregar;
    private javax.swing.JLabel lblCallePacienteAgregar;
    private javax.swing.JLabel lblCiudadPacienteAgregar;
    private javax.swing.JLabel lblColoniaPacienteAgregar;
    private javax.swing.JLabel lblCorreoPacienteAgregar;
    private javax.swing.JLabel lblCpPacienteAgregar;
    private javax.swing.JLabel lblEdoCivilPacienteAgregar;
    private javax.swing.JLabel lblEstadoPacienteAgregar;
    private javax.swing.JLabel lblGeneroPacienteAgregar;
    private javax.swing.JLabel lblNoExPacienteAgregar;
    private javax.swing.JLabel lblNoInPacienteAgregar;
    private javax.swing.JLabel lblNombrePacienteAgregar;
    private javax.swing.JLabel lblOcupacionPacienteAgregar;
    private javax.swing.JLabel lblTelefonoPacienteAgregar;
    private javax.swing.JTextField txtApellidosBuscarPaciente;
    private javax.swing.JTextField txtCalleBuscarPaciente;
    private javax.swing.JTextField txtCiudadBuscarPaciente;
    private javax.swing.JTextField txtClaveBuscarPaciente;
    private javax.swing.JTextField txtColoniaBuscarPaciente;
    private javax.swing.JTextField txtCorreoBuscarPaciente;
    private javax.swing.JTextField txtCpBuscarPaciente;
    private javax.swing.JTextField txtNoExBuscarPaciente;
    private javax.swing.JTextField txtNoInBuscarPaciente;
    private javax.swing.JTextField txtNombreBuscarPaciente;
    private javax.swing.JTextField txtOcupacionBuscarPaciente;
    private javax.swing.JTextField txtTelefonoBuscarPaciente;
    // End of variables declaration//GEN-END:variables
}
